name: dashboard-stack

networks:
  proxy:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/dozzle:/data
    networks:
      - proxy
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_AUTH_PROVIDER=simple
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.${TAILSCALE_DOMAIN}`) || Host(`dozzle.home.arpa`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    volumes:
      - ./config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - ${DATA_PATH}:/data:ro
      - ${JELLY_DATA_PATH}:/jelly-data:ro
      - ${THIRD_DISK_PATH}:/disk3:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "homepage.${TAILSCALE_DOMAIN},${TAILSCALE_DOMAIN}" # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_VAR_DOMAIN: "${TAILSCALE_DOMAIN}"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${TAILSCALE_DOMAIN}`) || Host(`homepage.home.arpa`) || Host(`${TAILSCALE_DOMAIN}`) || Host(`Host(home.arpa`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}:/srv/data:ro
      - ${JELLY_DATA_PATH}:/srv/jelly-data:ro
      - ./config/filebrowser:/config
    environment:
      - FB_DATABASE=/config/filebrowser.db
      - FB_ROOT=/srv
      # - FB_NOAUTH=true  # or set up auth via filebrowser config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${TAILSCALE_DOMAIN}`) || Host(`files.home.arpa`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./config/kuma:/app/data
    environment:
      - TZ=UTC  # Set the timezone (change to your preferred local timezone so monitoring times are the same)
      - UMASK=0022
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kuma.rule=Host(`kuma.${TAILSCALE_DOMAIN}`) || Host(`kuma.home.arpa`)"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
    ports:
      - 8080:8080
    volumes:
      - /run/udev:/run/udev:ro
      - ./config/scrutiny/config:/opt/scrutiny/config
      - ./config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - SCRUTINY_NOTIFY_URLS=${SCRUTINY_NOTIFY_URLS}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.${TAILSCALE_DOMAIN}`) || Host(`scrutiny.home.arpa`)"
      - "traefik.http.routers.scrutiny.entrypoints=websecure"
      - "traefik.http.routers.scrutiny.tls=true"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./config/beszel:/beszel_data
    environment:
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.beszel.rule=Host(`beszel.${TAILSCALE_DOMAIN}`) || Host(`beszel.home.arpa`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /media/huyen/MainDisk:/extra-filesystems/MainDisk:ro
      - /media/huyen/TestHDD:/extra-filesystems/TestHDD:ro
      - /media/huyen/Disk2:/extra-filesystems/Disk2:ro
      - /media/huyen/Parity:/extra-filesystems/Parity:ro
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHRBd0MsCBNPQ1e5kTN4E/0EMTL7vGtlmwweKAyLFTYq'
      TOKEN: cad1ab16-977b-48e9-a59f-c855fa3beb33
      HUB_URL: https://beszel.${TAILSCALE_DOMAIN}
