---
title: my homelab
description: Home Lab Dashboard

background:
  image: https://images2.alphacoders.com/129/thumb-1920-1295497.png
  blur: md
  saturate: 100
  brightness: 30
  opacity: 50

cardBlur: sm

color: slate
theme: dark

headerStyle: clean

language: en

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true

layout:
  Tools:
    style: row
    columns: 3
    icon: mdi-tools
  Media:
    style: row
    columns: 3
    icon: mdi-play-circle
  Media Management:
    style: row
    columns: 2
    icon: mdi-download-circle
  Monitor:
    style: row
    columns: 4
    icon: mdi-monitor
  Infrastructure:
    style: row
    columns: 3
    icon: mdi-server
