---
- resources:
    label: System
    cpu: true
    memory: true
    expanded: true
    disk:
      - /
      - /data
      - /jelly-data
      - /disk3

- openmeteo:
    label: Singapore
    latitude: 1.3521
    longitude: 103.8198
    timezone: Asia/Singapore
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
