name: stirling

networks:
  proxy:
    external: true

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./config:/configs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.services.rule=Host(`pdf.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.services.entrypoints=websecure"
      - "traefik.http.routers.services.tls=true"
      - "traefik.http.services.stirling.loadbalancer.server.port=8080"
