name: nextcloud-stack

networks:
  proxy:
    external: true
  default:

services:
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
    restart: unless-stopped
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NC_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NC_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - default

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${NC_REDIS_PASSWORD}
    networks:
      - default

  nextcloud-imaginary:
    image: nextcloud/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    networks:
      - default

  nextcloud-collabora:
    image: collabora/code:latest
    container_name: nextcloud-collabora
    restart: unless-stopped
    environment:
      - aliasgroup1=https://nextcloud.${PUBLIC_DOMAIN}
      - DONT_GEN_SSL_CERT=YES
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    networks:
      - proxy
    extra_hosts:
      - "nextcloud.${PUBLIC_DOMAIN}:172.19.0.2"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.collabora.rule=Host(`collabora.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
      - nextcloud-imaginary
      - nextcloud-collabora
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${NC_REDIS_PASSWORD}
      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NC_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${PUBLIC_DOMAIN} nextcloud-app
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_HOSTNAME=nextcloud.${PUBLIC_DOMAIN}
      - NC_default_phone_region=SG
      - IMAGINARY_HOST=nextcloud-imaginary
    volumes:
      - ./config/nextcloud-main:/var/www/html
      - ${DATA_PATH}:/var/www/html/data
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nc-rep,nc-header"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      # CalDAV/CardDAV redirect
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      # Security headers
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
