name: tools

networks:
  proxy:
    external: true

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./config/stirling:/configs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls=true"
      - "traefik.http.routers.stirling-pdf.service=stirling-pdf"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - JWT_SECRET=hP83eH8b7REyepzmMjUAy8PVuFwVaY3EkaARhgKLbq4ivmM9Ysygpe4D1gTQ8fTz # will use randomUUID() if unset
      - MAX_CONVERT_PROCESS=1
      # - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection
    volumes:
      - ./config/convertx:/app/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.convertx.rule=Host(`convert.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.convertx.entrypoints=websecure"
      - "traefik.http.routers.convertx.tls=true"
      - "traefik.http.routers.convertx.service=convertx"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"

  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    restart: unless-stopped
    volumes:
      - ./config/microbin:/app/microbin_data
    environment:
      MICROBIN_PUBLIC_PATH: "https://paste.${PUBLIC_DOMAIN}"
      MICROBIN_BIND: "0.0.0.0"
      MICROBIN_PORT: "8080"

      # Useful defaults
      MICROBIN_TITLE: "Paste"
      MICROBIN_HIGHLIGHTSYNTAX: "true"
      MICROBIN_PRIVATE: "true"
      MICROBIN_NO_LISTING: "true"
      MICROBIN_QR: "true"
      MICROBIN_ENABLE_BURN_AFTER: "true"
      MICROBIN_DEFAULT_EXPIRY: "1week"

      # Auth
      MICROBIN_BASIC_AUTH_USERNAME: "${MICROBIN_USER}"
      MICROBIN_BASIC_AUTH_PASSWORD: "${MICROBIN_PASSWORD}"

      # Optional: disable file uploads if you only want text/logs
      MICROBIN_NO_FILE_UPLOAD: "true"

      # Optional privacy
      MICROBIN_DISABLE_TELEMETRY: "true"
      MICROBIN_DISABLE_UPDATE_CHECKING: "true"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.microbin.rule=Host(`paste.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.microbin.entrypoints=websecure"
      - "traefik.http.routers.microbin.tls=true"
      - "traefik.http.routers.microbin.service=microbin"
      - "traefik.http.services.microbin.loadbalancer.server.port=8080"
